---
- hosts: all
  become: true
  vars:

    nombre: Santiago
    apellido: Godoy
    division: 116
  tasks:
    - include_role:
        name: 2do_parcial
    - name: Crear archivo alumno con template
      template:
        src: alumno.j2
        dest: /tmp/2do_parcial/alumno/datos_alumno.txt

    - name: Crear archivo equipo con template
      template:
        src: equipo.j2
        dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    - name: Configurar sudoers sin password
      copy:
        dest: /etc/sudoers.d/2PSupervisores
        content: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"
